import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { APP_TITLE } from "@/constants";
import { Navbar } from "@/ui/organisms/navbar";
import { Footer } from "@/ui/organisms/Footer";
import { Dropdown } from "@/ui/molecules/dropdown";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: APP_TITLE,
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={`${inter.className} h-screen flex flex-col`}>
				<header>
					<Navbar>
						<Dropdown	
							options={[
								{ href: "/collections", children: "Collections" },
								{ href: "/categories", children: "Categories" },
							]} 
							selected={{ href: "/", children: "Home" }} 
						/>
					</Navbar>
				</header>
				<main>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
